apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: ecommerce-project
spec:
  type: ClusterIP
  ports:
    - port: 1024
      targetPort: 1024
      name: grpc
  selector:
    app: auth-app