apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce-project
spec:
  type: ClusterIP
  ports:
    - port: 54320
      targetPort: 5432
      name: postgres
  selector:
    app: postgres
