apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ecommerce-project
spec:
  type: ClusterIP
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  selector:
    app: rabbitmq
