apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: ecommerce-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-service
          image: 291041007391.dkr.ecr.ap-southeast-1.amazonaws.com/ecommerce/gateway:1
          ports:
            - name: http
              protocol: TCP
              containerPort: 1234
          env:
            - name: auth
              value: auth-svc:1024
            - name: JWT_SECRET
              value: secret