server:
  ha:
    enabled: true
  ha:
    raft:
         enabled: true
         setNodeId: true
         config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path    = "/vault/data/"
            }

            listener "tcp" {
               address = "[::]:8200"
               cluster_address = "[::]:8201"
               tls_disable = "true"
            }
            service_registration "kubernetes" {}
  dataStorage:
    enabled: true
    storageClass: ebs-gp3
  service:
    type: ClusterIP
  serviceAccount:
    create: false
    name: vault
