// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: inventories.proto

package Inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // Current page number
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Total         *int32                 `protobuf:"varint,4,opt,name=total,proto3,oneof" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_inventories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreID       int32                  `protobuf:"varint,1,opt,name=StoreID,proto3" json:"StoreID,omitempty"`
	AddBy         string                 `protobuf:"bytes,2,opt,name=AddBy,proto3" json:"AddBy,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ImageURL      string                 `protobuf:"bytes,5,opt,name=ImageURL,proto3" json:"ImageURL,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=Price,proto3" json:"Price,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=Stock,proto3" json:"Stock,omitempty"`
	CategoryID    int32                  `protobuf:"varint,8,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	ID            int32                  `protobuf:"varint,9,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_inventories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{1}
}

func (x *Inventory) GetStoreID() int32 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

func (x *Inventory) GetAddBy() string {
	if x != nil {
		return x.AddBy
	}
	return ""
}

func (x *Inventory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Inventory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Inventory) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *Inventory) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Inventory) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Inventory) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Inventory) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type AddInvenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=Inventory,proto3" json:"Inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInvenRequest) Reset() {
	*x = AddInvenRequest{}
	mi := &file_inventories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInvenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInvenRequest) ProtoMessage() {}

func (x *AddInvenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInvenRequest.ProtoReflect.Descriptor instead.
func (*AddInvenRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{2}
}

func (x *AddInvenRequest) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type AddInvenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInvenResponse) Reset() {
	*x = AddInvenResponse{}
	mi := &file_inventories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInvenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInvenResponse) ProtoMessage() {}

func (x *AddInvenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInvenResponse.ProtoReflect.Descriptor instead.
func (*AddInvenResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{3}
}

func (x *AddInvenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateInvenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvetoriesID  string                 `protobuf:"bytes,1,opt,name=InvetoriesID,proto3" json:"InvetoriesID,omitempty"`
	Inventory     *Inventory             `protobuf:"bytes,2,opt,name=Inventory,proto3" json:"Inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvenRequest) Reset() {
	*x = UpdateInvenRequest{}
	mi := &file_inventories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvenRequest) ProtoMessage() {}

func (x *UpdateInvenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvenRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvenRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateInvenRequest) GetInvetoriesID() string {
	if x != nil {
		return x.InvetoriesID
	}
	return ""
}

func (x *UpdateInvenRequest) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type UpdateInvenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvenResponse) Reset() {
	*x = UpdateInvenResponse{}
	mi := &file_inventories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvenResponse) ProtoMessage() {}

func (x *UpdateInvenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvenResponse.ProtoReflect.Descriptor instead.
func (*UpdateInvenResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInvenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveInvenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvetoriesID  int32                  `protobuf:"varint,1,opt,name=InvetoriesID,proto3" json:"InvetoriesID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInvenRequest) Reset() {
	*x = RemoveInvenRequest{}
	mi := &file_inventories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInvenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInvenRequest) ProtoMessage() {}

func (x *RemoveInvenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInvenRequest.ProtoReflect.Descriptor instead.
func (*RemoveInvenRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveInvenRequest) GetInvetoriesID() int32 {
	if x != nil {
		return x.InvetoriesID
	}
	return 0
}

type RemoveInvenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInvenResponse) Reset() {
	*x = RemoveInvenResponse{}
	mi := &file_inventories_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInvenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInvenResponse) ProtoMessage() {}

func (x *RemoveInvenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInvenResponse.ProtoReflect.Descriptor instead.
func (*RemoveInvenResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveInvenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetInvetoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvetoriesID  int32                  `protobuf:"varint,1,opt,name=InvetoriesID,proto3" json:"InvetoriesID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvetoryRequest) Reset() {
	*x = GetInvetoryRequest{}
	mi := &file_inventories_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvetoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvetoryRequest) ProtoMessage() {}

func (x *GetInvetoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvetoryRequest.ProtoReflect.Descriptor instead.
func (*GetInvetoryRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{8}
}

func (x *GetInvetoryRequest) GetInvetoriesID() int32 {
	if x != nil {
		return x.InvetoriesID
	}
	return 0
}

type GetInvetoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=Inventory,proto3" json:"Inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvetoryResponse) Reset() {
	*x = GetInvetoryResponse{}
	mi := &file_inventories_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvetoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvetoryResponse) ProtoMessage() {}

func (x *GetInvetoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvetoryResponse.ProtoReflect.Descriptor instead.
func (*GetInvetoryResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{9}
}

func (x *GetInvetoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type ListInvetoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvetoriesRequest) Reset() {
	*x = ListInvetoriesRequest{}
	mi := &file_inventories_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvetoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvetoriesRequest) ProtoMessage() {}

func (x *ListInvetoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvetoriesRequest.ProtoReflect.Descriptor instead.
func (*ListInvetoriesRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{10}
}

func (x *ListInvetoriesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListInvetoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     []*Inventory           `protobuf:"bytes,1,rep,name=Inventory,proto3" json:"Inventory,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvetoriesResponse) Reset() {
	*x = ListInvetoriesResponse{}
	mi := &file_inventories_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvetoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvetoriesResponse) ProtoMessage() {}

func (x *ListInvetoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvetoriesResponse.ProtoReflect.Descriptor instead.
func (*ListInvetoriesResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{11}
}

func (x *ListInvetoriesResponse) GetInventory() []*Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *ListInvetoriesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryID    int32                  `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StoreID       int32                  `protobuf:"varint,3,opt,name=StoreID,proto3" json:"StoreID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_inventories_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{12}
}

func (x *Category) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetStoreID() int32 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

type AddCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCategoryRequest) Reset() {
	*x = AddCategoryRequest{}
	mi := &file_inventories_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryRequest) ProtoMessage() {}

func (x *AddCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryRequest.ProtoReflect.Descriptor instead.
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{13}
}

func (x *AddCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCategoryResponse) Reset() {
	*x = AddCategoryResponse{}
	mi := &file_inventories_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryResponse) ProtoMessage() {}

func (x *AddCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryResponse.ProtoReflect.Descriptor instead.
func (*AddCategoryResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{14}
}

func (x *AddCategoryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	CategoryID    int32                  `protobuf:"varint,2,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	StoreID       int32                  `protobuf:"varint,3,opt,name=StoreID,proto3" json:"StoreID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_inventories_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *UpdateCategoryRequest) GetStoreID() int32 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_inventories_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCategoryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveCatgoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryID    int32                  `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCatgoryRequest) Reset() {
	*x = RemoveCatgoryRequest{}
	mi := &file_inventories_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCatgoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCatgoryRequest) ProtoMessage() {}

func (x *RemoveCatgoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCatgoryRequest.ProtoReflect.Descriptor instead.
func (*RemoveCatgoryRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveCatgoryRequest) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

type RemoveCatgoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCatgoryResponse) Reset() {
	*x = RemoveCatgoryResponse{}
	mi := &file_inventories_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCatgoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCatgoryResponse) ProtoMessage() {}

func (x *RemoveCatgoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCatgoryResponse.ProtoReflect.Descriptor instead.
func (*RemoveCatgoryResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveCatgoryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreID       int32                  `protobuf:"varint,1,opt,name=StoreID,proto3" json:"StoreID,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_inventories_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{19}
}

func (x *ListCategoriesRequest) GetStoreID() int32 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

func (x *ListCategoriesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListCategoriesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catagories    []*Category            `protobuf:"bytes,1,rep,name=Catagories,proto3" json:"Catagories,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_inventories_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{20}
}

func (x *ListCategoriesResponse) GetCatagories() []*Category {
	if x != nil {
		return x.Catagories
	}
	return nil
}

func (x *ListCategoriesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_inventories_proto protoreflect.FileDescriptor

const file_inventories_proto_rawDesc = "" +
	"\n" +
	"\x11inventories.proto\x12\fInventory.v1\"s\n" +
	"\n" +
	"pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x19\n" +
	"\x05total\x18\x04 \x01(\x05H\x00R\x05total\x88\x01\x01B\b\n" +
	"\x06_total\"\xe9\x01\n" +
	"\tInventory\x12\x18\n" +
	"\aStoreID\x18\x01 \x01(\x05R\aStoreID\x12\x14\n" +
	"\x05AddBy\x18\x02 \x01(\tR\x05AddBy\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x1a\n" +
	"\bImageURL\x18\x05 \x01(\tR\bImageURL\x12\x14\n" +
	"\x05Price\x18\x06 \x01(\x01R\x05Price\x12\x14\n" +
	"\x05Stock\x18\a \x01(\x05R\x05Stock\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\b \x01(\x05R\n" +
	"CategoryID\x12\x0e\n" +
	"\x02ID\x18\t \x01(\x05R\x02ID\"H\n" +
	"\x0fAddInvenRequest\x125\n" +
	"\tInventory\x18\x01 \x01(\v2\x17.Inventory.v1.InventoryR\tInventory\"*\n" +
	"\x10AddInvenResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"o\n" +
	"\x12UpdateInvenRequest\x12\"\n" +
	"\fInvetoriesID\x18\x01 \x01(\tR\fInvetoriesID\x125\n" +
	"\tInventory\x18\x02 \x01(\v2\x17.Inventory.v1.InventoryR\tInventory\"-\n" +
	"\x13UpdateInvenResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"8\n" +
	"\x12RemoveInvenRequest\x12\"\n" +
	"\fInvetoriesID\x18\x01 \x01(\x05R\fInvetoriesID\"-\n" +
	"\x13RemoveInvenResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"8\n" +
	"\x12GetInvetoryRequest\x12\"\n" +
	"\fInvetoriesID\x18\x01 \x01(\x05R\fInvetoriesID\"L\n" +
	"\x13GetInvetoryResponse\x125\n" +
	"\tInventory\x18\x01 \x01(\v2\x17.Inventory.v1.InventoryR\tInventory\"/\n" +
	"\x15ListInvetoriesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\"\x89\x01\n" +
	"\x16ListInvetoriesResponse\x125\n" +
	"\tInventory\x18\x01 \x03(\v2\x17.Inventory.v1.InventoryR\tInventory\x128\n" +
	"\n" +
	"Pagination\x18\x02 \x01(\v2\x18.Inventory.v1.paginationR\n" +
	"Pagination\"X\n" +
	"\bCategory\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x01 \x01(\x05R\n" +
	"CategoryID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aStoreID\x18\x03 \x01(\x05R\aStoreID\"(\n" +
	"\x12AddCategoryRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"-\n" +
	"\x13AddCategoryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"e\n" +
	"\x15UpdateCategoryRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x02 \x01(\x05R\n" +
	"CategoryID\x12\x18\n" +
	"\aStoreID\x18\x03 \x01(\x05R\aStoreID\"0\n" +
	"\x16UpdateCategoryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"6\n" +
	"\x14RemoveCatgoryRequest\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x01 \x01(\x05R\n" +
	"CategoryID\"/\n" +
	"\x15RemoveCatgoryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x83\x01\n" +
	"\x15ListCategoriesRequest\x12\x18\n" +
	"\aStoreID\x18\x01 \x01(\x05R\aStoreID\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x128\n" +
	"\n" +
	"Pagination\x18\x03 \x01(\v2\x18.Inventory.v1.paginationR\n" +
	"Pagination\"\x8a\x01\n" +
	"\x16ListCategoriesResponse\x126\n" +
	"\n" +
	"Catagories\x18\x01 \x03(\v2\x16.Inventory.v1.CategoryR\n" +
	"Catagories\x128\n" +
	"\n" +
	"Pagination\x18\x02 \x01(\v2\x18.Inventory.v1.paginationR\n" +
	"Pagination2\xac\x06\n" +
	"\x10InventoryService\x12M\n" +
	"\fAddInventory\x12\x1d.Inventory.v1.AddInvenRequest\x1a\x1e.Inventory.v1.AddInvenResponse\x12V\n" +
	"\x0fUpdateInventory\x12 .Inventory.v1.UpdateInvenRequest\x1a!.Inventory.v1.UpdateInvenResponse\x12V\n" +
	"\x0fRemoveInventory\x12 .Inventory.v1.RemoveInvenRequest\x1a!.Inventory.v1.RemoveInvenResponse\x12S\n" +
	"\fGetInventory\x12 .Inventory.v1.GetInvetoryRequest\x1a!.Inventory.v1.GetInvetoryResponse\x12\\\n" +
	"\x0fListInventories\x12#.Inventory.v1.ListInvetoriesRequest\x1a$.Inventory.v1.ListInvetoriesResponse\x12R\n" +
	"\vAddCategory\x12 .Inventory.v1.AddCategoryRequest\x1a!.Inventory.v1.AddCategoryResponse\x12[\n" +
	"\x0eUpdateCategory\x12#.Inventory.v1.UpdateCategoryRequest\x1a$.Inventory.v1.UpdateCategoryResponse\x12X\n" +
	"\rRemoveCatgory\x12\".Inventory.v1.RemoveCatgoryRequest\x1a#.Inventory.v1.RemoveCatgoryResponse\x12[\n" +
	"\x0eListCategories\x12#.Inventory.v1.ListCategoriesRequest\x1a$.Inventory.v1.ListCategoriesResponseB\rZ\v./Inventoryb\x06proto3"

var (
	file_inventories_proto_rawDescOnce sync.Once
	file_inventories_proto_rawDescData []byte
)

func file_inventories_proto_rawDescGZIP() []byte {
	file_inventories_proto_rawDescOnce.Do(func() {
		file_inventories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventories_proto_rawDesc), len(file_inventories_proto_rawDesc)))
	})
	return file_inventories_proto_rawDescData
}

var file_inventories_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_inventories_proto_goTypes = []any{
	(*Pagination)(nil),             // 0: Inventory.v1.pagination
	(*Inventory)(nil),              // 1: Inventory.v1.Inventory
	(*AddInvenRequest)(nil),        // 2: Inventory.v1.AddInvenRequest
	(*AddInvenResponse)(nil),       // 3: Inventory.v1.AddInvenResponse
	(*UpdateInvenRequest)(nil),     // 4: Inventory.v1.UpdateInvenRequest
	(*UpdateInvenResponse)(nil),    // 5: Inventory.v1.UpdateInvenResponse
	(*RemoveInvenRequest)(nil),     // 6: Inventory.v1.RemoveInvenRequest
	(*RemoveInvenResponse)(nil),    // 7: Inventory.v1.RemoveInvenResponse
	(*GetInvetoryRequest)(nil),     // 8: Inventory.v1.GetInvetoryRequest
	(*GetInvetoryResponse)(nil),    // 9: Inventory.v1.GetInvetoryResponse
	(*ListInvetoriesRequest)(nil),  // 10: Inventory.v1.ListInvetoriesRequest
	(*ListInvetoriesResponse)(nil), // 11: Inventory.v1.ListInvetoriesResponse
	(*Category)(nil),               // 12: Inventory.v1.Category
	(*AddCategoryRequest)(nil),     // 13: Inventory.v1.AddCategoryRequest
	(*AddCategoryResponse)(nil),    // 14: Inventory.v1.AddCategoryResponse
	(*UpdateCategoryRequest)(nil),  // 15: Inventory.v1.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil), // 16: Inventory.v1.UpdateCategoryResponse
	(*RemoveCatgoryRequest)(nil),   // 17: Inventory.v1.RemoveCatgoryRequest
	(*RemoveCatgoryResponse)(nil),  // 18: Inventory.v1.RemoveCatgoryResponse
	(*ListCategoriesRequest)(nil),  // 19: Inventory.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil), // 20: Inventory.v1.ListCategoriesResponse
}
var file_inventories_proto_depIdxs = []int32{
	1,  // 0: Inventory.v1.AddInvenRequest.Inventory:type_name -> Inventory.v1.Inventory
	1,  // 1: Inventory.v1.UpdateInvenRequest.Inventory:type_name -> Inventory.v1.Inventory
	1,  // 2: Inventory.v1.GetInvetoryResponse.Inventory:type_name -> Inventory.v1.Inventory
	1,  // 3: Inventory.v1.ListInvetoriesResponse.Inventory:type_name -> Inventory.v1.Inventory
	0,  // 4: Inventory.v1.ListInvetoriesResponse.Pagination:type_name -> Inventory.v1.pagination
	0,  // 5: Inventory.v1.ListCategoriesRequest.Pagination:type_name -> Inventory.v1.pagination
	12, // 6: Inventory.v1.ListCategoriesResponse.Catagories:type_name -> Inventory.v1.Category
	0,  // 7: Inventory.v1.ListCategoriesResponse.Pagination:type_name -> Inventory.v1.pagination
	2,  // 8: Inventory.v1.InventoryService.AddInventory:input_type -> Inventory.v1.AddInvenRequest
	4,  // 9: Inventory.v1.InventoryService.UpdateInventory:input_type -> Inventory.v1.UpdateInvenRequest
	6,  // 10: Inventory.v1.InventoryService.RemoveInventory:input_type -> Inventory.v1.RemoveInvenRequest
	8,  // 11: Inventory.v1.InventoryService.GetInventory:input_type -> Inventory.v1.GetInvetoryRequest
	10, // 12: Inventory.v1.InventoryService.ListInventories:input_type -> Inventory.v1.ListInvetoriesRequest
	13, // 13: Inventory.v1.InventoryService.AddCategory:input_type -> Inventory.v1.AddCategoryRequest
	15, // 14: Inventory.v1.InventoryService.UpdateCategory:input_type -> Inventory.v1.UpdateCategoryRequest
	17, // 15: Inventory.v1.InventoryService.RemoveCatgory:input_type -> Inventory.v1.RemoveCatgoryRequest
	19, // 16: Inventory.v1.InventoryService.ListCategories:input_type -> Inventory.v1.ListCategoriesRequest
	3,  // 17: Inventory.v1.InventoryService.AddInventory:output_type -> Inventory.v1.AddInvenResponse
	5,  // 18: Inventory.v1.InventoryService.UpdateInventory:output_type -> Inventory.v1.UpdateInvenResponse
	7,  // 19: Inventory.v1.InventoryService.RemoveInventory:output_type -> Inventory.v1.RemoveInvenResponse
	9,  // 20: Inventory.v1.InventoryService.GetInventory:output_type -> Inventory.v1.GetInvetoryResponse
	11, // 21: Inventory.v1.InventoryService.ListInventories:output_type -> Inventory.v1.ListInvetoriesResponse
	14, // 22: Inventory.v1.InventoryService.AddCategory:output_type -> Inventory.v1.AddCategoryResponse
	16, // 23: Inventory.v1.InventoryService.UpdateCategory:output_type -> Inventory.v1.UpdateCategoryResponse
	18, // 24: Inventory.v1.InventoryService.RemoveCatgory:output_type -> Inventory.v1.RemoveCatgoryResponse
	20, // 25: Inventory.v1.InventoryService.ListCategories:output_type -> Inventory.v1.ListCategoriesResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_inventories_proto_init() }
func file_inventories_proto_init() {
	if File_inventories_proto != nil {
		return
	}
	file_inventories_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventories_proto_rawDesc), len(file_inventories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventories_proto_goTypes,
		DependencyIndexes: file_inventories_proto_depIdxs,
		MessageInfos:      file_inventories_proto_msgTypes,
	}.Build()
	File_inventories_proto = out.File
	file_inventories_proto_goTypes = nil
	file_inventories_proto_depIdxs = nil
}
