---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups: ["*"]
  resources: ["deployments", "pods", "services", "namespaces"]
  verbs: ["get", "list", "watch"]