---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  namespace: ecommerce-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-app
  template:
    metadata:
      labels:
        app: jaeger-app
    spec:
      containers:
        - name: jaeger-app
          image: jaegertracing/all-in-one:1.6.0
          ports:
            - protocol: TCP
              containerPort: 14268
            - protocol: TCP
              containerPort: 16686
            - protocol: TCP
              containerPort: 5778
            - protocol: TCP
              containerPort: 9411
            - protocol: UDP
              containerPort: 5775
            - protocol: UDP
              containerPort: 6831
            - protocol: UDP
              containerPort: 6832